"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$env_var\
$directory\
$git_branch\
$git_status\
$character"""

[env_var.STARSHIP_OSX]
format = "[$env_value]($style) "
style = "bold red"

[env_var.STARSHIP_LINUX]
format = "[$env_value]($style) "
style = "bold purple"

[directory]
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " "

[git_status]
style = "bold red"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
